name = "registry-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-29"
[[kv_namespaces]]
binding = "REGISTRY_MAPS"
id = "2404769202a04df4b2dd93e63f08788a"
[dev]
ip = "127.0.0.1"
port = 8888
local_protocol = "https"
